### ISSUE TITLE
using strategy.spinnaker.io/replace: "true" on a non-versioned resource does not work

### ISSUE THREAD

**Issue by billiford** [homedepot/go-clouddriver#157]
Using `strategy.spinnaker.io/replace: "true"` on a non-versioned resource that exists does not actually deploy the resource. There is no error thrown, but any changes to the resource YAML are not actually applied to the cluster.

The [Strategy Documentation](https://spinnaker.io/docs/reference/providers/kubernetes-v2/#strategy) does state that the resource should be versioned:
> When set to 'true' for a **versioned** resource, this will update your resources using replace.

I find this misleading and a bad experience. I should be able to replace an existing resource whether it's versioned or not.

Code to inspect here: https://github.com/homedepot/go-clouddriver/blob/7a6b08e35d17c54c1ddb420d7508274ea2a8fb3a/internal/kubernetes/client.go#L187-L203

To recreate:
1) deploy a simple config map
```yaml
apiVersion: v1
data:
  test.json: |
    {"test":"test"}
kind: ConfigMap
metadata:
  annotations:
    strategy.spinnaker.io/versioned: 'false'
  name: test-config
```
2) deploy the config map again using the replace strategy and changing the data
```yaml
apiVersion: v1
data:
  test.json: |
    {"test":"test-replace"}
kind: ConfigMap
metadata:
  annotations:
    strategy.spinnaker.io/versioned: 'false'
    strategy.spinnaker.io/replace: 'true'
  name: test-config
```
3) observe that the second config map does not get deployed to the cluster
```
$ kubectl get cm test-config -o yaml
apiVersion: v1
data:
  test.json: |
    {"test":"test"}
...
```
